# Generated by Django 4.2.23 on 2025-08-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HagiographyOrWrittenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literary_source_type', models.CharField(choices=[('Lives', 'Lives'), ('Miracles', 'Miracles'), ('Accounts of martyrdom', 'Accounts of martyrdom'), ('New testament', 'New testament'), ('Other', 'Other')], max_length=25)),
                ('date_or_century_of_source', models.CharField(max_length=20)),
                ('title_literary_text', models.TextField()),
                ('liturgical_texts_source_type', models.CharField(choices=[('Liturgical compilation', 'Liturgical compilation'), ('Hymns', 'Hymns'), ('Other', 'Other')], max_length=25)),
                ('date_or_century_of_liturgical_source', models.CharField(max_length=20)),
                ('title_liturgical_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Hagiography or Written Source',
                'verbose_name_plural': 'Hagiographies and Written Sources',
                'ordering': ['title_literary_text'],
            },
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10)),
                ('type_of_saint', models.CharField(choices=[('Bishop', 'Bishop'), ('Monk-Ascetic', 'Monk-Ascetic'), ('Hermit-Recluse', 'Hermit-Recluse'), ('Martyr', 'Martyr'), ('Deacon', 'Deacon'), ('Other', 'Other')], max_length=20)),
                ('act_period', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('Unknown', 'Unknown')], max_length=10)),
                ('region_of_birth', models.TextField()),
                ('region_of_burial', models.TextField()),
                ('feast_day', models.CharField(blank=True, help_text='Format: MM-DD (e.g., 12-25 for December 25)', max_length=5, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=50, null=True)),
                ('death_date', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('secondary_feast_date', models.CharField(blank=True, help_text='Format: MM-DD (e.g., 01-19 for January 19)', max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Saint',
                'verbose_name_plural': 'Saints',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaintTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('miracle', 'Miracle'), ('canonization', 'Canonization'), ('other', 'Other')], max_length=20)),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='saints.saint')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_references', to='saints.hagiographyorwrittensource')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['saint', 'date'],
            },
        ),
        migrations.CreateModel(
            name='SaintBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('building_type', models.CharField(choices=[('Church', 'Church'), ('Chapel', 'Chapel'), ('Monastery', 'Monastery'), ('Shrine', 'Shrine'), ('Other', 'Other')], max_length=20)),
                ('location', models.TextField()),
                ('construction_date', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='saints.saint')),
            ],
            options={
                'verbose_name': 'Saint Building',
                'verbose_name_plural': 'Saint Buildings',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='saint_images/')),
                ('material_technique', models.CharField(choices=[('Wall Painting', 'Wall Painting'), ('Icon', 'Icon'), ('Manuscript', 'Manuscript'), ('Sculpture', 'Sculpture'), ('Other', 'Other')], max_length=20)),
                ('site_monument', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('century', models.CharField(choices=[('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('13th', '13th'), ('14th', '14th'), ('15th', '15th'), ('16th', '16th')], max_length=4)),
                ('location_of_portrait', models.CharField(choices=[('Sanctuary', 'Sanctuary'), ('Naos', 'Naos'), ('Narthex', 'Narthex'), ('Other', 'Other')], max_length=20)),
                ('location_description', models.TextField()),
                ('iconographic_type', models.CharField(choices=[('Portrait', 'Portrait'), ('Scene', 'Scene of life'), ('Other', 'Other')], max_length=20)),
                ('has_inscription', models.BooleanField(default=False)),
                ('inscription_text', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('copyright_info', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='saints.saint')),
            ],
            options={
                'verbose_name': 'Saint Image',
                'verbose_name_plural': 'Saint Images',
            },
        ),
        migrations.AddField(
            model_name='hagiographyorwrittensource',
            name='saint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hagiographies', to='saints.saint'),
        ),
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=50, null=True)),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliographies', to='saints.saint')),
            ],
            options={
                'verbose_name_plural': 'Bibliographies',
            },
        ),
        migrations.CreateModel(
            name='AspectsOfCult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cult_place', models.TextField()),
                ('pilgrimage_site', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Lost', 'Lost')], max_length=8)),
                ('activities_accompanying_cult', models.TextField(help_text='Describe rituals, festivals, or other activities')),
                ('relics_cult_related_objects', models.TextField(help_text='Describe any relics or objects associated with the cult')),
                ('miracles', models.TextField()),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cult_aspects', to='saints.saint')),
            ],
            options={
                'verbose_name': 'Aspect of Cult',
                'verbose_name_plural': 'Aspects of Cult',
            },
        ),
        migrations.CreateModel(
            name='ArchaeologicalAndArchitecturalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cult_buildings', models.CharField(choices=[('Church', 'Church'), ('Chapel', 'Chapel'), ('Monastic Building', 'Monastic Building'), ('Crypt', 'Crypt'), ('Tomb', 'Tomb'), ('Sarcophagus', 'Sarcophagus'), ("Saint's Life Site", "Place associated with saint's life"), ('Holy Spring', 'Holy spring'), ('Other', 'Other')], max_length=50)),
                ('date', models.CharField(help_text='Year or approximate date', max_length=20)),
                ('current_condition', models.TextField(help_text='Description of current condition')),
                ('location', models.TextField()),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archaeological_evidence', to='saints.saint')),
            ],
            options={
                'verbose_name': 'Archaeological and Architectural Evidence',
                'verbose_name_plural': 'Archaeological and Architectural Evidences',
            },
        ),
    ]
