# Generated by Django 4.2.7 on 2025-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter height in meters (e.g., 1.20 for 1.2 meters)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter width in meters (e.g., 0.85 for 0.85 meters)', max_digits=5, null=True),
        ),
    ]
