# Generated by Django 4.2.7 on 2025-09-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0002_alter_image_height_alter_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saint',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
