# Generated by Django 4.2.7 on 2025-09-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0003_alter_saint_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Century',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='saint',
            name='act_period_text',
            field=models.CharField(blank=True, help_text='Optional free text if uncertain', max_length=100),
        ),
        migrations.AddField(
            model_name='saint',
            name='act_periods',
            field=models.ManyToManyField(blank=True, help_text='Select one or more centuries', to='saints.century'),
        ),
    ]
