# Generated by Django 4.2.7 on 2025-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0004_century_saint_act_period_text_saint_act_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saint',
            name='act_periods',
        ),
        migrations.DeleteModel(
            name='Century',
        ),
        migrations.AddField(
            model_name='saint',
            name='act_periods',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more centuries'),
        ),
    ]
