# Generated by Django 4.2.7 on 2025-09-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0005_remove_saint_act_periods_delete_century_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saint',
            name='act_period',
        ),
        migrations.RemoveField(
            model_name='saint',
            name='act_periods',
        ),
        migrations.AddField(
            model_name='saint',
            name='act_period_1',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('Unknown', 'Unknown')], help_text='Primary period of activity', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='saint',
            name='act_period_2',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('Unknown', 'Unknown')], help_text='Secondary period of activity (if applicable)', max_length=10, null=True),
        ),
    ]
