# Generated by Django 4.2.7 on 2025-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0006_remove_saint_act_period_remove_saint_act_periods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saint',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='saint',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='saint',
            name='secondary_feast_date',
        ),
        migrations.RemoveField(
            model_name='saint',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='saint',
            name='feast_day',
            field=models.CharField(blank=True, help_text='Feast Date (Month-Day, e.g., Jan 06)', max_length=6, null=True),
        ),
    ]
