# Generated by Django 4.2.7 on 2025-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0007_remove_saint_birth_date_remove_saint_death_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archaeologicalandarchitecturalevidence',
            name='date',
        ),
        migrations.AddField(
            model_name='archaeologicalandarchitecturalevidence',
            name='act_period_1',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('13th', '13th'), ('14th', '14th'), ('15th', '15th'), ('16th', '16th'), ('Unknown', 'Unknown')], help_text='Primary period of activity', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='archaeologicalandarchitecturalevidence',
            name='act_period_2',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('13th', '13th'), ('14th', '14th'), ('15th', '15th'), ('16th', '16th'), ('Unknown', 'Unknown')], help_text='Secondary period of activity (if applicable)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='archaeologicalandarchitecturalevidence',
            name='act_period_text',
            field=models.CharField(blank=True, help_text='Optional free text if uncertain', max_length=100),
        ),
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='cult_buildings',
            field=models.CharField(choices=[('Cult building - Church', 'Cult building - Church'), ('Cult building - Chapel', 'Cult building - Chapel'), ('Cult building - Monastic Building', 'Cult building - Monastic Building'), ('Burial site - Crypt', 'Burial site - Crypt'), ('Burial site - Tomb', 'Burial site - Tomb'), ('Burial site - Sarcophagus', 'Burial site - Sarcophagus'), ("Saint's Life Site", "Place associated with saint's life"), ('Holy Spring', 'Holy spring'), ('Other', 'Other')], max_length=50),
        ),
    ]
