# Generated by Django 4.2.7 on 2025-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0008_remove_archaeologicalandarchitecturalevidence_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archaeologicalandarchitecturalevidence',
            old_name='act_period_1',
            new_name='date_1',
        ),
        migrations.RenameField(
            model_name='archaeologicalandarchitecturalevidence',
            old_name='act_period_2',
            new_name='date_2',
        ),
        migrations.RenameField(
            model_name='archaeologicalandarchitecturalevidence',
            old_name='act_period_text',
            new_name='date_text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='copyright_info',
        ),
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='image',
            name='source',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='current_condition',
            field=models.CharField(choices=[('In use', 'In use'), ('Ruin', 'Ruin'), ('Restored', 'Restored'), ('Excavated', 'Excavated'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='location_of_portrait',
            field=models.CharField(choices=[('Sanctuary', 'Sanctuary'), ('Naos', 'Naos'), ('Narthex', 'Narthex')], max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='material_technique',
            field=models.CharField(choices=[('Wall Painting', 'Wall Painting'), ('Icon', 'Icon'), ('Other', 'Other')], max_length=20),
        ),
    ]
