# Generated by Django 4.2.7 on 2025-09-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0009_rename_act_period_1_archaeologicalandarchitecturalevidence_date_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliography',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='image',
            name='location_of_portrait_text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='iconographic_type',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('Scene', 'Scene of life')], max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='site_monument',
            field=models.TextField(blank=True, null=True),
        ),
    ]
