# Generated by Django 4.2.7 on 2025-09-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0010_remove_bibliography_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaintTimeline',
        ),
    ]
