# Generated by Django 4.2.7 on 2025-09-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0011_delete_sainttimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='cult_buildings',
            field=models.CharField(blank=True, choices=[('Cult building - Church', 'Cult building - Church'), ('Cult building - Chapel', 'Cult building - Chapel'), ('Cult building - Monastic Building', 'Cult building - Monastic Building'), ('Burial site - Crypt', 'Burial site - Crypt'), ('Burial site - Tomb', 'Burial site - Tomb'), ('Burial site - Sarcophagus', 'Burial site - Sarcophagus'), ("Saint's Life Site", "Place associated with saint's life"), ('Holy Spring', 'Holy spring'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='current_condition',
            field=models.CharField(blank=True, choices=[('In use', 'In use'), ('Ruin', 'Ruin'), ('Restored', 'Restored'), ('Excavated', 'Excavated'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='date_1',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('13th', '13th'), ('14th', '14th'), ('15th', '15th'), ('16th', '16th'), ('Unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='date_2',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('13th', '13th'), ('14th', '14th'), ('15th', '15th'), ('16th', '16th'), ('Unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='date_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archaeologicalandarchitecturalevidence',
            name='saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archaeological_evidence', to='saints.saint'),
        ),
        migrations.AlterField(
            model_name='aspectsofcult',
            name='activities_accompanying_cult',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspectsofcult',
            name='cult_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspectsofcult',
            name='miracles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspectsofcult',
            name='pilgrimage_site',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='aspectsofcult',
            name='relics_cult_related_objects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspectsofcult',
            name='saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cult_aspects', to='saints.saint'),
        ),
        migrations.AlterField(
            model_name='aspectsofcult',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Lost', 'Lost')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bibliographies', to='saints.saint'),
        ),
        migrations.AlterField(
            model_name='hagiographyorwrittensource',
            name='date_or_century_of_liturgical_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hagiographyorwrittensource',
            name='date_or_century_of_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hagiographyorwrittensource',
            name='literary_source_type',
            field=models.CharField(blank=True, choices=[('Lives', 'Lives'), ('Miracles', 'Miracles'), ('Accounts of martyrdom', 'Accounts of martyrdom'), ('New testament', 'New testament'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='hagiographyorwrittensource',
            name='liturgical_texts_source_type',
            field=models.CharField(blank=True, choices=[('Liturgical compilation', 'Liturgical compilation'), ('Hymns', 'Hymns'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='hagiographyorwrittensource',
            name='saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hagiographies', to='saints.saint'),
        ),
        migrations.AlterField(
            model_name='hagiographyorwrittensource',
            name='title_literary_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hagiographyorwrittensource',
            name='title_liturgical_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='century',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('13th', '13th'), ('14th', '14th'), ('15th', '15th'), ('16th', '16th')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='has_inscription',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='iconographic_type',
            field=models.CharField(blank=True, choices=[('Portrait', 'Portrait'), ('Scene', 'Scene of life')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='saint_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location_of_portrait',
            field=models.CharField(blank=True, choices=[('Sanctuary', 'Sanctuary'), ('Naos', 'Naos'), ('Narthex', 'Narthex')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='location_of_portrait_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='material_technique',
            field=models.CharField(blank=True, choices=[('Wall Painting', 'Wall Painting'), ('Icon', 'Icon'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='saints.saint'),
        ),
        migrations.AlterField(
            model_name='saint',
            name='act_period_1',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('Unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='act_period_2',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('Unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='act_period_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='feast_day',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='region_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='region_of_burial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='type_of_saint',
            field=models.CharField(blank=True, choices=[('Bishop', 'Bishop'), ('Monk-Ascetic', 'Monk-Ascetic'), ('Hermit-Recluse', 'Hermit-Recluse'), ('Martyr', 'Martyr'), ('Deacon', 'Deacon'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saintbuilding',
            name='building_type',
            field=models.CharField(blank=True, choices=[('Church', 'Church'), ('Chapel', 'Chapel'), ('Monastery', 'Monastery'), ('Shrine', 'Shrine'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saintbuilding',
            name='construction_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saintbuilding',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saintbuilding',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saintbuilding',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='saintbuilding',
            name='saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='saints.saint'),
        ),
    ]
