# Generated by Django 4.2.7 on 2025-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0012_alter_archaeologicalandarchitecturalevidence_cult_buildings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='region_of_birth_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='saint',
            name='region_of_birth_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='saint',
            name='region_of_burial_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='saint',
            name='region_of_burial_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
