# Generated by Django 5.1.6 on 2025-10-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0014_archaeologicalandarchitecturalevidence_cult_buildings_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark this as the default image'),
        ),
    ]
